name: "build and test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  appleclang:
    name: appleclang-11.0.3
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install boost cryptopp
    - name: pgp-packet-library
      run: |
        git clone https://github.com/summitto/pgp-packet-library.git
        git -C pgp-packet-library submodule update --init --recursive
        cmake -B pgp-packet-library/build -S pgp-packet-library -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=ci-install
        cmake --build pgp-packet-library/build --target install
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=ci-install
    - name: build
      run: cmake --build build
    - name: test
      run: make -C build test
